# Generated by Django 3.1.5 on 2021-09-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
