# Generated by Django 3.1.5 on 2021-09-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('percent_off', models.IntegerField()),
                ('usages', models.IntegerField(default=0)),
                ('max_usages', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
